import { FONT_FAMILY } from '@assets/fonts';
import { TextType } from '@types';
import { TextStyle } from 'react-native';

export const fontFamily: TextType<string> = {
  'bold-2xl': FONT_FAMILY.bold,
  'bold-xl': FONT_FAMILY.bold,
  'bold-lg': FONT_FAMILY.bold,
  'bold-base': FONT_FAMILY.bold,
  'bold-sm': FONT_FAMILY.bold,
  'bold-xs': FONT_FAMILY.bold,
  'bold-2xs': FONT_FAMILY.bold,
  'regular-2xl': FONT_FAMILY.regular,
  'regular-xl': FONT_FAMILY.regular,
  'regular-lg': FONT_FAMILY.regular,
  'regular-base': FONT_FAMILY.regular,
  'regular-sm': FONT_FAMILY.regular,
  'regular-xs': FONT_FAMILY.regular,
  'regular-2xs': FONT_FAMILY.regular,
  'light-2xl': FONT_FAMILY.light,
  'light-xl': FONT_FAMILY.light,
  'light-lg': FONT_FAMILY.light,
  'light-base': FONT_FAMILY.light,
  'light-sm': FONT_FAMILY.light,
  'light-xs': FONT_FAMILY.light,
  'light-2xs': FONT_FAMILY.light,
};

export const fontWeight: TextType<TextStyle['fontWeight']> = {
  'bold-2xl': '700',
  'bold-xl': '700',
  'bold-lg': '700',
  'bold-base': '700',
  'bold-sm': '700',
  'bold-xs': '700',
  'bold-2xs': '700',
  'regular-2xl': '400',
  'regular-xl': '400',
  'regular-lg': '400',
  'regular-base': '400',
  'regular-sm': '400',
  'regular-xs': '400',
  'regular-2xs': '400',
  'light-2xl': '300',
  'light-xl': '300',
  'light-lg': '300',
  'light-base': '300',
  'light-sm': '300',
  'light-xs': '300',
  'light-2xs': '300',
};

export const fontSize: TextType<number> = {
  'bold-2xl': 24,
  'bold-xl': 20,
  'bold-lg': 16,
  'bold-base': 14,
  'bold-sm': 12,
  'bold-xs': 10,
  'bold-2xs': 8,
  'regular-2xl': 24,
  'regular-xl': 20,
  'regular-lg': 16,
  'regular-base': 14,
  'regular-sm': 12,
  'regular-xs': 10,
  'regular-2xs': 8,
  'light-2xl': 24,
  'light-xl': 20,
  'light-lg': 16,
  'light-base': 14,
  'light-sm': 12,
  'light-xs': 10,
  'light-2xs': 8,
};

export const lineHeight: TextType<number> = {
  'bold-2xl': 30,
  'bold-xl': 25,
  'bold-lg': 20,
  'bold-base': 18,
  'bold-sm': 15,
  'bold-xs': 12,
  'bold-2xs': 10,
  'regular-2xl': 30,
  'regular-xl': 25,
  'regular-lg': 20,
  'regular-base': 18,
  'regular-sm': 15,
  'regular-xs': 12,
  'regular-2xs': 10,
  'light-2xl': 30,
  'light-xl': 25,
  'light-lg': 20,
  'light-base': 18,
  'light-sm': 15,
  'light-xs': 12,
  'light-2xs': 10,
};
